import CountingSort from './counting_sort';
import DagShortestPath from './dag_shortest_path';
import DijkstraBinaryHeap from './dijkstra_binary_heap';
import DijkstraSimpleArray from './disjkstra_simple_array';
import HeapSort from './heap_sort';
import InsertionSortLoop from './insertion_sort_loop';
import MergeSortLoop from './merge_sort_loop';
import QuickSort from './quick_sort';
import RadixSort from './radix_sort';
import SelectionSort from './selection_sort_loop';
import TopologicalSort from './topological_sort';
import BellmanFord from './bellman_ford';
import FindNegativeWeightCycle from './find_negative_weight_cycle';

// CountingSort.test();
// DagShortestPath.test();
// DijkstraBinaryHeap.test();
// DijkstraSimpleArray.test();
// HeapSort.test();
// InsertionSortLoop.test();
// MergeSortLoop.test();
// QuickSort.test();
// RadixSort.test();
// SelectionSort.test();
// TopologicalSort.test();
BellmanFord.test();